wandb_version: 1

input_shape:
  desc: null
  value:
  - 1
  - 28
  - 28
num_classes:
  desc: null
  value: 10
population_size:
  desc: null
  value: 10
num_generations:
  desc: null
  value: 5
mutation_rate:
  desc: null
  value: 0.3
elite_size:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1738618286.0
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.16.5
      8:
      - 3
      - 5
      13: windows-amd64
